before_commands:
  - composer update --prefer-source --dev --no-interaction
tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c .scrutinizer-ci.phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ['src/', 'tests/']
    php_cpd:
        enabled: true
        names:
            - '*.php'
        excluded_dirs: ['build', 'examples', 'tests', 'vendor']
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ['src/', 'tests/']
    php_loc:
        enabled: true
        excluded_dirs: ['build', 'examples', 'tests', 'vendor']
    php_mess_detector:
        enabled: true
        filter:
            paths: ['src/']
    php_pdepend:
        enabled: true
        excluded_dirs: ['build', 'examples', 'tests', 'vendor']
    php_analyzer:
        enabled: true
        filter:
            paths: ['src/', 'tests/']
    sensiolabs_security_checker:
        enabled: true