build:
    environment:
        php: '5.6.9'
        mysql: true
        timezone: 'Europe/London'
    dependencies:
        before:
            - sudo apt-get update
    project_setup:
        before:
            - echo "{\"config\":{\"github-oauth\":{\"github.com\":\"b570db4db20d2cb79386fe8e55485bbe3f6141dc\"}}}" | sudo tee ~/.composer/config.json
            - sudo composer self-update
            - composer update --prefer-source --no-interaction
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
    sensiolabs_security_checker:
        enabled: true
filter:
    excluded_paths:
      - tests/*
      - bin/*
      - build/*
      - vendor/*
      - examples/*

checks:
    php:
        code_rating: true
        duplication: true